# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Idiot Coding
subtitle: subtitle
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

  Here I chronicle my idiot coding. I'm not pretending to anything I don't have.
  I've been programming a few years now and I'm still amazed by
  my own idiocy. Hopefully, you can learn from my mistakes here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: suttsp
github_username:  spence95

# Build settings
markdown: kramdown
