# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: spence's blog
subtitle: Programming
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

  I've got ham but I'm not a hamster.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: suttsp
github_username:  spence95

# Build settings
markdown: kramdown
